name: Node CI

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
    types: [opened, synchronize, reopened, assigned]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          node --version
          yarn --version
          yarn install --frozen-lockfile

      - name: Build and test
        run: |
          yarn build
          yarn test --silent --coverage
        env:
          CI: true
