name: Size

on:
  pull_request:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@271282ca25e92249d56092e277f42b5db527ccb0
